### ISSUE TITLE
org-babel-load-session:prolog has unnecessary parameters

### ISSUE THREAD

**Issue by lafrenierejm** [ljos/ob-prolog#15]
The [function definition of `org-babel-load-session:prolog`](https://github.com/ljos/ob-prolog/blob/efa86bb70fd1907806f3e43705aff54d35582442/ob-prolog.el#L137) has unnecessary BODY and PARAMS parameters.

`body` is never used in the function's body.  The only thing `params` is used for in the function is a `let*` binding of `params`;  that new, lexically-scoped `params` is never used.

**Comment by ljos** [comment]
This is because `org-babel-load-in-session` uses it like that.  I think I just copied this from somewhere when I was learning how ob-babel worked. I can see now that `org-babel-load-session:prolog` is not doing everything it is supposed to. It doesn't load body into the session as the documentation for `load-in-session` says. We should fix this.

**Comment by lafrenierejm** [comment]
Can you elaborate on your understanding of what `org-babel-load-in-session` is supposed to do?

Neither [micanzhang/ob-rust](https://github.com/micanzhang/ob-rust/tree/f23d93725c21ab95a44cb4d2c0c4ab0489bd55d9) nor [krisajenkins/ob-translate](https://github.com/krisajenkins/ob-translate/tree/9d9054a51bafd5a29a8135964069b4fa3a80b169) (commits referenced are those used by MELPA as of this posting) implement `org-babel-load-in-session`.  The built-in `emacs-lisp` babel also appears to not implement the function.

**Comment by ljos** [comment]
I have to investigate when it is used. It looks to me that `org-babel-load-in-session` uses it to load the source block with the variables into the current session and then switches to a window with that buffer in it.

**Comment by ljos** [comment]
`org-babel-load-in-session` doesn't seem to be implemented by a lot of modes, but it seems `org-babel-load-in-session` is bound to `C-l`.

**Comment by ljos** [comment]
`load-in-session` is a built in org-babel command.

**Comment by lafrenierejm** [comment]
If "session" means what I think it does, then a working implementation of `org-babel-load-in-session` seems that it could be very useful for Prolog.  In the meantime, do you think it would be prudent to remove the current, nonfunctional definition of `org-babel-load-in-session`?

Do you have any guarantees that the other code dealing with sessions is behaving correctly?

**Comment by ljos** [comment]
The `org-babel-prolog-evaluate-session` code should work. It did last time I worked with it. The `org-babel-load-session:prolog` code doesn't do what it is supposed to as it only opens the session. It doesn't actually evaluate the current block. 

I see that other modes that implement session handling, like `ob-R`, they also have a `org-babel-prep-session:MODE` function. That converts the stuff like variables etc. 

It should be fairly simple to refactor out the clause loading from `org-babel-prolog-evaluate-session` and create a new function that can be used in `prep-session`. Then `load-session` can use `prep-session`. The clause handeling is a little strange because of how the prolog repl behaves, but it shouldn't be too difficult.

I am also wondering if there are other commands that org-babel expects that it would be good for prolog to implement.
